# Generated by Django 2.1.1 on 2019-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('price', models.CharField(max_length=64, verbose_name='price')),
                ('image', models.CharField(max_length=128, verbose_name='image')),
                ('release_date', models.DateField(verbose_name='release_date')),
                ('lte_exists', models.CharField(max_length=64, verbose_name='lte_exists')),
                ('slug', models.CharField(max_length=64, verbose_name='slug')),
            ],
        ),
    ]
