# Generated by Django 2.1.1 on 2019-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20190822_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samsung',
            name='touch_id',
            field=models.CharField(max_length=64, verbose_name='TouchId'),
        ),
    ]
