# Generated by Django 2.1.1 on 2019-08-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20190822_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apple',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='apple',
            name='smart_touch',
        ),
        migrations.RemoveField(
            model_name='huawei',
            name='flashlight',
        ),
        migrations.RemoveField(
            model_name='huawei',
            name='lense',
        ),
        migrations.RemoveField(
            model_name='samsung',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='samsung',
            name='touch_id',
        ),
        migrations.RemoveField(
            model_name='samsung',
            name='wifi',
        ),
        migrations.AddField(
            model_name='apple',
            name='addon',
            field=models.CharField(default='None', max_length=64, verbose_name='Addon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huawei',
            name='addon',
            field=models.CharField(default='None', max_length=64, verbose_name='Addon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samsung',
            name='addon',
            field=models.CharField(default='None', max_length=64, verbose_name='Addon'),
            preserve_default=False,
        ),
    ]
